### ISSUE TITLE
is Omnifocus 3 broken?

### ISSUE THREAD

**Issue by yeled** [seattlerb/omnifocus-github#13]
Does this work for anymore with Omnifocus3?

```
% of sync

Ignoring nokogiri-1.8.3 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.3
/Users/yeled/.gem/gems/rb-scpt-1.0.2/lib/_appscript/terminology.rb:57: warning: assigned but unused variable - rev
/Users/yeled/.gem/gems/rb-scpt-1.0.2/lib/_appscript/safeobject.rb:230: warning: method redefined; discarding old method_added
/Users/yeled/.gem/gems/rb-scpt-1.0.2/lib/_appscript/safeobject.rb:239: warning: method redefined; discarding old included
/Users/yeled/.gem/gems/rb-scpt-1.0.2/lib/rb-scpt.rb:542:in `_send_command': CommandError (Appscript::CommandError)
                OSERROR: -1743
                COMMAND: app("/Applications/OmniFocus.app").default_document.flattened_projects.tasks.get()
        from /Users/yeled/.gem/gems/rb-scpt-1.0.2/lib/rb-scpt.rb:642:in `method_missing'
        from /Users/yeled/.gem/gems/omnifocus-2.3.0/lib/omnifocus.rb:91:in `all_tasks'
        from /Users/yeled/.gem/gems/omnifocus-2.3.0/lib/omnifocus.rb:129:in `prepopulate_existing_tasks'
        from /Users/yeled/.gem/gems/omnifocus-2.3.0/lib/omnifocus.rb:246:in `cmd_sync'
        from /Users/yeled/.gem/gems/omnifocus-2.3.0/lib/omnifocus.rb:276:in `method_missing'
        from /Users/yeled/.gem/gems/omnifocus-2.3.0/bin/of:17:in `<top (required)>'
        from /Users/yeled/bin/of:22:in `load'
        from /Users/yeled/bin/of:22:in `<main>'

```

**Comment by zenspider** [comment]
I was entirely unaware that there was a version 3. My own OF didn't bother to tell me of this. As such, I don't have a version I can test against (yet). Want to take a whack at it?

**Comment by zenspider** [comment]
Also, do you have a pro license?

**Comment by yeled** [comment]
Yes this is Pro.

I have been following the release notes, but they haven't mentioned any Applescript changes.

However I just tested it again with `3.1.2 (v120.6 r320379)` and my `of sync` works again!

🎉
